### ISSUE TITLE
Typo in /spring/data-access.properties

### ISSUE THREAD

**Issue by cybuch** [thymeleaf/thymeleafexamples-petclinic#8]
I guess it should be
# jdbc.initLocation=classpath:db/mysql/initDB.sql
# jdbc.dataLocation=classpath:db/mysql/populateDB.sql

instead of
# jdbc.initLocation=classpath:db/mysql/initDB.txt
# jdbc.dataLocation=classpath:db/mysql/populateDB.txt

**Comment by mrnoway** [comment]
thank you smart genius :)

You surely just saved the Day for me!
If you change this, uncomment the MySql Stuff in pom.xml;
It works flawless!

'Little piece of advice from me" MySQL Root user does require a Password,
if you password is blank you can never connect successfully.

And one more: petclinic_db_setup_mysql.txt
Step 1 is needed:
Step 2: the first part the JDBC Connector .jar file is not needed to put anywhere: "Alternatively", this would should be changed to "HAVE TO DO"
Step 3: "db/mysql/createDB.txt" this should be "createDB.sql"
Step 4: "src/main/resources/spring/jdbc.properties" this is wrong, it must be 
            "src/main/resources/spring/data-access.properties"

I hope I could help someone.

best regards

**Comment by danielfernandez** [comment]
Fixed by #10
